# datasource
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  hikari:
    jdbc-url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        #show_sql: true
        format_sql: true


# logging
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
